### ISSUE TITLE
Usage for different language

### ISSUE THREAD

**Issue by MichalGabonay** [dair-iitd/OpenIE-standalone#25]
It is a possibility to somehow use this project for different languages from English? I need OpenIE for Czech and Slovak language. Can be just used another language model? If yes, are there some special requirements for this language model? How big dependency is on WordNet? 

Thank you.

**Comment by swarnaHub** [comment]
I think porting this project into some other language is not straight-forward. The primary requirement is that of a dependency parser. We use Clear for parsing English sentences. I don't know about Czech and Slovak parsers. Even if they are good, you might not be able to plug it in directly in the code. We use the binarised Berkeley LM. If you use some other LMs, they might not support the queries that the Berkeley one does, making it difficult to integrate directly. The dependency on Wordnet is mostly for numerical sentences, so that's not huge.
