### ISSUE TITLE
Unresolved Dependency Path issue

### ISSUE THREAD

**Issue by DShivansh** [dair-iitd/OpenIE-standalone#31]
So I am trying to build OpenIE on my machine and the error is coming that is 
sbt.librarymanagement.ResolveException: unresolved dependency: edu.washington.cs.knowitall.srlie#srlie_2.10;1.0.4-SNAPSHOT: not found

can anyone help me out with this its is urgent.

**Comment by Fortune-Don** [comment]
I have the same problem now. Have you solved the problem yet? If so, could you tell me how?

**Comment by abhisheksms** [comment]
> I have the same problem now. Have you solved the problem yet? If so, could you tell me how?

Try [this](https://stackoverflow.com/questions/45817763/sbt-always-coming-up-with-unresolved-dependency-error). It states that the file "build.properties" must set sbt.version to 0.13.x.

**Comment by amandalmia14** [comment]
@DShivansh Will you able to solve the error, if yes how? Which version of sbt you have used.

I am trying to build in Windows 10. 

@abjoker, I tried with 0.13.8 version of SBT, still showing the same error.

**Comment by abhisheksms** [comment]
@amandalmia14  I used 0.13.0 version

```sbt.version=0.13.0```

**Comment by amandalmia14** [comment]
@abjoker Have you build in Ubuntu?

**Comment by abhisheksms** [comment]
@amandalmia14  yes, however choice of OS shouldn't be a problem i guess

**Comment by amandalmia14** [comment]
@abjoker I wasn't able to find the same version in Windows. 
https://www.scala-sbt.org/download.html

I tried with sbt 0.13.15 but it didn't worked.

**Comment by abhisheksms** [comment]
@amandalmia14  I used google colab since I did not have enough memory requirements, I was able to run the jar files but I could not use the actual functionality of converting text data to triples, since it requires another instance(similar to a new command prompt tab) which isn't possible in colab smh :-(

I am not sure of Windows 10, you can try with sbt version 1.2.1 (or something like that which was originally mentioned in build.properties)

**Comment by usbader** [comment]
sbt 0.13.0 is not listed in the download page.
